### PR TITLE
csi-debug: command to check network conn b/w csi

### PR DESCRIPTION
**Pull request by subhamkrai**
with new command `csi-debug test-connection` we can verify the connection between csi-cephfs/rbd and ceph cluster.

Signed-off-by: subhamkrai <srai@redhat.com>

### CODE REVIEW

**Comment by subhamkrai** [comment]
part of #69

**Comment by subhamkrai** [comment]
sample output

```console
csi-debug test-connection 
Info: checking 'csi-cephfsplugin-provisioner' network connection
Info: Network connection between cluster and csi-cephfs is: Connected

Info: checking 'csi-rbdplugin-provisioner' network connection
Info: Network connection between cluster and csi-rbd is: Connected
```

**Review by travisn — CHANGES_REQUESTED** [review]
What about making this part of a "csi health" command?
```
kubectl rook-ceph csi health
```

Then we can add more checks over time to this same command that show different parts of the health of the csi driver.

**Comment by subhamkrai** [comment]
We are moving the project to golang, so it is not a valid change. Closing!

**Pull request closed without merging**
