### PR TITLE
Redirect logs to stderr.

### PR DESCRIPTION
**Pull request by lunderhage**
Core: redirect log messages to stderr

The PR redirects the log messages to stderr so that the 
json output from some commands can be parsed with eg jq.

### CODE REVIEW

**Review by subhamkrai — CHANGES_REQUESTED** [review]
please sign-off  your commits

https://github.com/rook/rook/blob/master/Documentation/Contributing/development-flow.md#commit-structure

**Comment by subhamkrai** [comment]
@lunderhage can you update your pr commit message with something like

```
Core: redirect log messages to stderr

The PR redirects the log messages to stderr so that the 
json output from some commands can be parsed with eg jq.
```

Thanks

**Review by subhamkrai — COMMENTED** [review]
PR looks good to me and also working locally but somehow CI is not happy.
```
srai@192 ~ (pr/141) $ ./bin/kubectl-rook-ceph rbd ls replicapool
Warning: rook version 'rook: v1.12.0-alpha.0.10.g647a4e353' is running a pre-release version of Rook.

csi-vol-45398f0b-276c-4e93-ab33-df24dfb9dff8
```

@travisn do you see any immediate issue with the CI or we can go ahead with and debug CI in the follow up pr?

**Comment by travisn** [comment]
> @travisn do you see any immediate issue with the CI or we can go ahead with and debug CI in the follow up pr?

I don't immediately see the cause either. Does any other PR see this issue? Until we know it's not caused by this PR, let's troubleshoot before merging, otherwise the CI could be broken by this.

**Comment by subhamkrai** [comment]
> > @travisn do you see any immediate issue with the CI or we can go ahead with and debug CI in the follow up pr?
> 
> I don't immediately see the cause either. Does any other PR see this issue? Until we know it's not caused by this PR, let's troubleshoot before merging, otherwise the CI could be broken by this.

#142 should fix the ci issue

**Comment by subhamkrai** [comment]
@lunderhage please rebase your pr to get green CI. Thanks for the PR!

**Review by subhamkrai — APPROVED** [review]

**Pull request merged**
