### PR TITLE
csi: add test for `rbd ls` with rados namespace

### PR DESCRIPTION
**Pull request by OdedViner**
this pr introduces a new test to verify the  `rbd ls`
command functionality when working with rados namespaces.
the test ensures that rbd images are correctly listed
```
$ ./bin/kubectl-rook-ceph rbd ls
poolName            imageName                                     namespace    
--------            ---------                                     ---------    
blockpool-rados-ns  csi-vol-465d5545-b621-4adb-afd6-fd548dbd0062  namespace-a  
blockpool-rados-ns  ---                                           namespace-b  
replicapool         ---                                           ---  
```
when namespaces are configured.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by travisn** [comment]
Please add a description to the PR and commit message.

**Comment by OdedViner** [comment]
> Please add a description to the PR and commit message.

@travisn done

**Review by subhamkrai — COMMENTED** [review]
@OdedViner with this PR you are creating the resources and the test is already in place. Right?

**Comment by OdedViner** [comment]
> @OdedViner with this PR you are creating the resources and the test is already in place. Right?

@subhamkrai correct, the test is running `rbd ls`

**Review by subhamkrai — APPROVED** [review]

**Pull request merged**
